<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Interfaces\IEmoteRankingService.cs" />
    <Compile Remove="Interfaces\IMessageFactory.cs" />
    <Compile Remove="Interfaces\IMessageService.cs" />
    <Compile Remove="Services\EmoteRankingService.cs" />
    <Compile Remove="Services\MessageFactory.cs" />
    <Compile Remove="Services\MessageService.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Interfaces\IEmoteRankingService.cs" />
    <None Include="Interfaces\IMessageFactory.cs" />
    <None Include="Interfaces\IMessageService.cs" />
    <None Include="Services\EmoteRankingService.cs" />
    <None Include="Services\MessageFactory.cs" />
    <None Include="Services\MessageService.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.10" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OlliBot.Application\OlliBot.Application.csproj" />
    <ProjectReference Include="..\OlliBot.Domain\OlliBot.Domain.csproj" />
  </ItemGroup>

</Project>
