// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OlliBot.Data;

#nullable disable

namespace OlliBot.Migrations.EmoteRankingDBMigrations
{
    [DbContext(typeof(EmoteRankingDB))]
    partial class EmoteRankingDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("OlliBot.Data.EmoteCount", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("EmoteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTimeUpdated")
                        .HasColumnType("TEXT");

                    b.HasKey("GuildId", "EmoteId");

                    b.ToTable("EmoteCounts");
                });

            modelBuilder.Entity("OlliBot.Data.LastChannelMessage", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("MessageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildId", "ChannelId");

                    b.ToTable("LastChannelMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
