using MediatR;

namespace OlliBot.Application.HumbleBundle.GetUserHumbleBundleSubscriptions;
public record GetUserHumbleBundleSubscriptionsQuery(ulong DiscordId) : IRequest<GetUserHumbleBundleSubscriptionsResult>;