using OlliBot.Domain.Enums;

namespace OlliBot.Application.HumbleBundle.GetUserHumbleBundleSubscriptions;
public record GetUserHumbleBundleSubscriptionsResult(IReadOnlyCollection<HumbleBundleType> HumbleBundleTypes, bool Success);